alter table AUGUSTWOKSHOPS_OPERATION add constraint FK_AUGUSTWOKSHOPS_OPERATION_ON_MODEL foreign key (MODEL_ID) references AUGUSTWOKSHOPS_MODEL(ID);
create index IDX_AUGUSTWOKSHOPS_OPERATION_ON_MODEL on AUGUSTWOKSHOPS_OPERATION (MODEL_ID);
