-- begin AUGUSTWOKSHOPS_MODEL
alter table AUGUSTWOKSHOPS_MODEL add constraint FK_AUGUSTWOKSHOPS_MODEL_ON_WORK_SHOP foreign key (WORK_SHOP_ID) references AUGUSTWOKSHOPS_WORK_SHOP(ID)^
create index IDX_AUGUSTWOKSHOPS_MODEL_ON_WORK_SHOP on AUGUSTWOKSHOPS_MODEL (WORK_SHOP_ID)^
-- end AUGUSTWOKSHOPS_MODEL
-- begin AUGUSTWOKSHOPS_OPERATION
alter table AUGUSTWOKSHOPS_OPERATION add constraint FK_AUGUSTWOKSHOPS_OPERATION_ON_MODEL foreign key (MODEL_ID) references AUGUSTWOKSHOPS_MODEL(ID)^
create index IDX_AUGUSTWOKSHOPS_OPERATION_ON_MODEL on AUGUSTWOKSHOPS_OPERATION (MODEL_ID)^
-- end AUGUSTWOKSHOPS_OPERATION
-- begin AUGUSTWOKSHOPS_EMPLOYEE
alter table AUGUSTWOKSHOPS_EMPLOYEE add constraint FK_AUGUSTWOKSHOPS_EMPLOYEE_ON_WORK_SHOP foreign key (WORK_SHOP_ID) references AUGUSTWOKSHOPS_WORK_SHOP(ID)^
create index IDX_AUGUSTWOKSHOPS_EMPLOYEE_ON_WORK_SHOP on AUGUSTWOKSHOPS_EMPLOYEE (WORK_SHOP_ID)^
-- end AUGUSTWOKSHOPS_EMPLOYEE
-- begin AUGUSTWOKSHOPS_LABOR_INTENSITY
alter table AUGUSTWOKSHOPS_LABOR_INTENSITY add constraint FK_AUGUSTWOKSHOPS_LABOR_INTENSITY_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references AUGUSTWOKSHOPS_EMPLOYEE(ID)^
alter table AUGUSTWOKSHOPS_LABOR_INTENSITY add constraint FK_AUGUSTWOKSHOPS_LABOR_INTENSITY_ON_OPERATION foreign key (OPERATION_ID) references AUGUSTWOKSHOPS_OPERATION(ID)^
create index IDX_AUGUSTWOKSHOPS_LABOR_INTENSITY_ON_EMPLOYEE on AUGUSTWOKSHOPS_LABOR_INTENSITY (EMPLOYEE_ID)^
create index IDX_AUGUSTWOKSHOPS_LABOR_INTENSITY_ON_OPERATION on AUGUSTWOKSHOPS_LABOR_INTENSITY (OPERATION_ID)^
-- end AUGUSTWOKSHOPS_LABOR_INTENSITY
